### ISSUE TITLE
Crash with mod Earth to Java

### ISSUE THREAD

**Issue by BobzBlue** [Traben-0/solid_mobs#36]
Specifically but perhaps not limited to the "long_nosed_sheep"

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2024-08-15 12:37:00
Description: Ticking entity

java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 65
	at it.unimi.dsi.fastutil.objects.Object2BooleanOpenHashMap.rehash(Object2BooleanOpenHashMap.java:1308)
	at it.unimi.dsi.fastutil.objects.Object2BooleanOpenHashMap.insert(Object2BooleanOpenHashMap.java:255)
	at it.unimi.dsi.fastutil.objects.Object2BooleanOpenHashMap.put(Object2BooleanOpenHashMap.java:263)
	at traben.solid_mobs.SolidMobsMain.isExemptType(SolidMobsMain.java:102)
	at MC//net.minecraft.entity.Entity.handler$iij000$solid_mobs$sm$moveWalkingRider(Entity.java:22037)
	at MC//net.minecraft.entity.Entity.tick(Entity.java:488)
	at MC//net.minecraft.entity.LivingEntity.tick(LivingEntity.java:2468)
	at MC//net.minecraft.entity.mob.MobEntity.tick(MobEntity.java:372)
	at MC//net.minecraft.server.world.ServerWorld.mixinextras$bridge$method_5773$281(ServerWorld.java)
	at MC//net.minecraft.server.world.ServerWorld.wrapOperation$hip000$puzzleslib$tickNonPassenger(ServerWorld.java:18297)
	at MC//net.minecraft.server.world.ServerWorld.tickEntity(ServerWorld.java:770)
	at MC//net.minecraft.world.World.tickEntity(World.java:498)
	at MC//net.minecraft.server.world.ServerWorld.method_31420(ServerWorld.java:408)
	at MC//net.minecraft.world.EntityList.forEach(EntityList.java:54)
	at MC//net.minecraft.server.world.ServerWorld.tick(ServerWorld.java:372)
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer.java:1021)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:912)
	at MC//net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:114)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base@21.0.3/java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at it.unimi.dsi.fastutil.objects.Object2BooleanOpenHashMap.rehash(Object2BooleanOpenHashMap.java:1308)
	at it.unimi.dsi.fastutil.objects.Object2BooleanOpenHashMap.insert(Object2BooleanOpenHashMap.java:255)
	at it.unimi.dsi.fastutil.objects.Object2BooleanOpenHashMap.put(Object2BooleanOpenHashMap.java:263)
	at traben.solid_mobs.SolidMobsMain.isExemptType(SolidMobsMain.java:102)
	at MC//net.minecraft.entity.Entity.handler$iij000$solid_mobs$sm$moveWalkingRider(Entity.java:22037)
	at MC//net.minecraft.entity.Entity.tick(Entity.java:488)
	at MC//net.minecraft.entity.LivingEntity.tick(LivingEntity.java:2468)
	at MC//net.minecraft.entity.mob.MobEntity.tick(MobEntity.java:372)
	at MC//net.minecraft.server.world.ServerWorld.mixinextras$bridge$method_5773$281(ServerWorld.java)
	at MC//net.minecraft.server.world.ServerWorld.wrapOperation$hip000$puzzleslib$tickNonPassenger(ServerWorld.java:18297)
	at MC//net.minecraft.server.world.ServerWorld.tickEntity(ServerWorld.java:770)
	at MC//net.minecraft.world.World.tickEntity(World.java:498)
	at MC//net.minecraft.server.world.ServerWorld.method_31420(ServerWorld.java:408)
	at MC//net.minecraft.world.EntityList.forEach(EntityList.java:54)
Mixins in Stacktrace: None found

-- Entity being ticked --
Details:
	Entity Type: earthtojavamobs:long_nosed_sheep (slexom.earthtojava.entity.base.E2JBaseMonoColorSheepEntity)
	Entity ID: 6631
	Entity Name: Long Nosed Sheep
	Entity's Exact location: 1029.00, 77.00, -357.00
	Entity's Block location: World: (1029,77,-357), Section: (at 5,13,11 in 64,4,-23; chunk contains blocks 1024,-64,-368 to 1039,319,-353), Region: (2,-1; contains chunks 64,-32 to 95,-1, blocks 1024,-64,-512 to 1535,319,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null

**Comment by BobzBlue** [comment]
I have not been able to recreate the crash.
